---
title: Protesti u Srbiji
email: your_email@example.com
author: OKI
description: Oslobođenje od nametnute vlasti
baseurl: ''
url: https://protesti.srb.in.rs/
date_format: "%b %-d, %Y"
header_pages:
- about.md
- contact.html
- peticija.md
text:
  pagination:
    newer: Newer
    older: Older
  share_buttons:
    text: Share this post!
    facebook: Share on Facebook
    twitter: Share on Twitter
    googleplus: Share on Google+
    linkedin: Share on LinkedIn
    digg: Share on Digg
    tumblr: Share on Tumblr
    reddit: Share on Reddit
    stumbleupon: Share on StumbleUpon
    hackernews: Share on Hacker News
  post:
    updated: Updated
    minute_read: minute read
    related_posts: Related Posts
  index:
    coming_soon: Coming soon...
  contact:
    email: Email Address
    content: What would you like to say?
    subject: New submission!
    submit: Say Hello
    ajax:
      sending: sending..
      sent: Message sent!
      error: Error!
  thanks: Thanks for contacting us. We will reply as soon as possible.
  og_locale: en_US
markdown: kramdown
permalink: pretty
paginate: '4'
sass:
  style: compressed
plugins:
- jekyll-paginate
- jekyll-sitemap
exclude:
- Gemfile
- Gemfile.lock
- Rakefile
- README.md
- screenshot.png
- vendor
_schema:
  description: text_area
  header_pages:
  - type: text_field
